# Generated by Django 4.0.3 on 2022-04-18 05:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default=None, upload_to=accounts.models.user_directory_path),
        ),
    ]
