# Generated by Django 4.0.3 on 2022-04-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
