# Generated by Django 4.0.3 on 2022-04-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(upload_to='user_<django.db.models.fields.AutoField>/<function user_directory_path at 0x000001D931E57AC0>'),
        ),
    ]
