# Generated by Django 4.0.3 on 2022-04-18 06:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(upload_to=accounts.models.user_directory_path),
        ),
    ]
