# Generated by Django 4.0.3 on 2022-04-18 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
